### ISSUE TITLE
Timer added second solve

### ISSUE THREAD

**Issue by Ender436** [Speedy-Cuber/Rubiks-Cube-Timer#19]
I was doing some 2x2 solves, and when I hit the space bar to end the solve, it ended the solve, but also added a second solve that lasted 0s.

**Comment by Speedy-Cuber** [comment]
The way this was written, with the get_ch() command, means that unfortunately, it will grab characters and feed them to the program every time it runs through the get_ch() command in the main while loop. While I am soon going to release the last update for this cube timer, I will soon be making a much better timer based on what I learned from this timer.  The project is currently under wraps, and I hope to make it public a few months after I release the final version of this timer.
